### PR TITLE
Check exit code of external tools; python 3 support

### PR DESCRIPTION
**Pull request by sjaenick**
Hi,

I noticed that tdnascan.py does not check the exit code for all external command invocations; this PR:

* replaces all os.system() calls by subprocess.call() and subsequent checking of the return code
* adds support for python 3

I successfully applied your software to analyze several datasets with python 3.8, bwa 0.7.17, and
samtools 1.10.

### CODE REVIEW

**Comment by sunliang3361** [comment]
could you let me know which OS systems you used? can you update our README file also? so i can merge pull request. Thanks

**Comment by sjaenick** [comment]
Sure thing; tested for both Ubuntu 18.04 LTS and 20.04 LTS. I've updated the README

**Comment by sunliang3361** [comment]
Could you also update 'Software Dependencies' session in the README? Which python version did you use? Thanks

**Comment by sjaenick** [comment]
done

**Pull request merged**
